name: Branch checks on non-develop Branches

on:
  push:
    branches-ignore:
      - main
      - develop
      - release/**
      - dependabot/**
  workflow_dispatch:
env:
  VITE_APP_NAME: ${{ vars.VITE_APP_NAME }}

jobs:
  ci:
    name: Branch Checks
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Install pnpm and dependencies
        uses: ./.github/actions/pnpm-install
      - name: Run branch checks
        uses: ./.github/actions/branch-checks
      - name: Build webapp
        uses: ./.github/actions/build-webapp
      - name: Run test suite
        uses: ./.github/actions/tests
